title:              Erica Chen
email:              ericachen708190@gmail.com
description:        My Story
author:             Erica Chen
baseurl:            ""
url:                "https://ericachen1.github.io"

# Social Profiles
github_username:    ericachen1
facebook_username:  Erica Chen
instagram_username:  airwrecah
linkedin_username: erica-chen-

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
